### ISSUE TITLE
Use org link syntax to specify transclusion target

### ISSUE THREAD

**Issue by avivo** [whacked/transclusion-minor-mode#1]
Being able to specify headings (both in the same file and in other files) would also be very useful - there are actually several stackoverflow questions asking how to do this.

**Comment by whacked** [comment]
that sounds interesting, would you mind pointing me to some of this discussion?

**Comment by avivo** [comment]
Here are two closest I could quickly collect: 
- http://stackoverflow.com/questions/15328515/iso-transclusion-in-emacs-org-mode (though I guess this isn't precisely that)
- http://emacs.stackexchange.com/questions/12562/org-mode-headings-in-multiple-places-at-once-transclusion

Do I know you IRL?

**Comment by whacked** [comment]
The first link is actually what I read before concluding there isn't a popular transclusion mechanism (aside of freex-mode which has stopped).

In the second link I assume you're talking about editing org sections in different parts of a buffer that _belong to the same file_. That's indeed an interesting use case but it's quite a bit more difficult to implement, mostly because you'd have to track all the open overlays (and the current code only allows a single overlay for a single target file), and all the line number shifts as a result of inserting overlays. I'm sure it can be done though.

I doubt I'll be working on this functionality in the near future though because it's not an itch I have now. Also I am not keen on the idea of introducing special headers that indicate transclusion (vs the `#+INCLUDE` directive which is _de facto_ transclusion during export). The next logical candidate would be an org link, which would potientially look like `[[*heading][transcluded heading:1-9]]` where the `:1-9` indicates transclusion target. If you are interested in doing this, look at the `paragraph` case inside `freex-toggle-embed` and that's where the logic should go. AFAICT org links don't get special treatment with `org-element-type` so I don't know which native function it uses yet. It's somewhere inside `org.el:org-open-at-point`

As for your last remark, I'm sure the answer is no, but I do know there is an exact name collision at mit and maybe that's who you suspect :-)
